#Archivo donde especifique la instalacion de librerias y configuracion a la hora de crear mis contenedores personalizados.
#La imagen desde la que partimos osea la base
FROM httpd:2.4
#directorio de trabajo dentro del contenedor
WORKDIR /usr/local/apache2/htdocs
#Copiamos los archivos de src al contenedor, al directorio de trabajo
COPY ../src/ .
#Puerto en que escucha el contenedor
EXPOSE 80