#Archivo donde especifique la instalacion de librerias y configuracion a la hora de crear mis contenedores personalizados.
#La imagen desde la que partimos osea la base
FROM ubuntu
RUN apt update && apt install -yq --no-install-recommends \
    apache2 \
    # libapache2-mod-php7.2 \
    nano \
    curl \
    net-tools \
    iputils-ping
#directorio de trabajo dentro del contenedor
WORKDIR /var/www/html
#Copiamos los archivos de src al directorio de trabajo del contenedor
#el directorio . se refiere al contexto en docker-compose.yml que seria portfolio
COPY ./src/ .
#Puerto en que escucha el contenedor
EXPOSE 80

CMD apachectl -DFOREGROUND