#Archivo donde especifique la instalacion de librerias y configuracion a la hora de crear mis contenedores personalizados.
#La imagen desde la que partimos osea la base
FROM httpd:2.4
RUN apt update && apt install nano
#directorio de trabajo dentro del contenedor
WORKDIR /usr/local/apache2/htdocs
#Copiamos los archivos de src al directorio de trabajo del contenedor
#el directorio . se refiere al contexto en docker-compose.yml que seria portfolio
COPY ./src/ .
#Puerto en que escucha el contenedor
EXPOSE 80