#Archivo donde especifique la instalacion de librerias y configuracion a la hora de crear mis contenedores personalizados.
#La imagen desde la que partimos osea la base
FROM ubuntu
ARG USUARIO
#Instalacion
RUN apt update && apt install -yq --no-install-recommends \
     apache2 \
     nano \
     curl \
     net-tools iputils-ping
     
#Creacion de usuario
RUN useradd -rm -d /home/${USUARIO} -s /bin/bash ${USUARIO}
#cambio de contraseña usuario:contraseña
RUN echo "${USUARIO}:usuario" | chpasswd
#directorio de trabajo dentro del contenedor
WORKDIR /var/www/html
#Copiamos los archivos de src al directorio de trabajo del contenedor
#el directorio . se refiere al contexto en docker-compose.yml que seria portfolio
COPY ./src/ .
#Puerto en que escucha el contenedor
EXPOSE 80
#Comando que se ejecuta al iniciar el contenedor
CMD apachectl -DFOREGROUND